### ISSUE TITLE
org.apache.thrift.protocol.TProtocolException: Required field 'keyspace' was not present!

### ISSUE THREAD

**Issue by sonyjv** [tuplejump/calliope-release#15]
Hi,

I have setup an EC2 cluster for Spark 0.9.1 and Datastax Cassandra Enterprise 4.5 using their respective official AMI. 

When I try to run one of the Spark application on AWS which is using Calliope Snapshot - 0.9.0-U1-C2-EA, I am getting the following error on starting. 

The same application was working perfectly in my local cluster with the same version of Spark and Cassandra. Could you please help me in resolving the issue. We are kind of in a deadlock situation. 

WARNING: Loss was due to java.lang.RuntimeException
java.lang.RuntimeException: org.apache.thrift.protocol.TProtocolException: Required field 'keyspace' was not present! Struct: set_keyspace_args(keyspace:null)
        at org.apache.cassandra.hadoop.cql3.CqlPagingRecordReader.initialize(CqlPagingRecordReader.java:161)
        at com.tuplejump.calliope.cql3.Cql3CassandraRDD$$anon$1.<init>(Cql3CassandraRDD.scala:65)
        at com.tuplejump.calliope.cql3.Cql3CassandraRDD.compute(Cql3CassandraRDD.scala:53)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:241)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:232)
        at org.apache.spark.rdd.FilteredRDD.compute(FilteredRDD.scala:33)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:241)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:232)
        at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:241)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:232)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:161)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
        at org.apache.spark.scheduler.Task.run(Task.scala:53)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$run$1.apply$mc
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.s
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.s
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInforma
        at org.apache.spark.deploy.SparkHadoopUtil.runAsUser(SparkHadoopUtil.sca
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
        at java.lang.Thread.run(Thread.java:744)
Jul 07, 2014 7:54:03 PM org.apache.spark.Logging$class logInfo

Thanks,
Sony

**Comment by milliondreams** [comment]
Hi Sony,

Though we don't test against and hence support working against DSE 4.5 I'll do my best to get your cluster going.

Can you give **0.9.4-EA-SNAPSHOT** build a try. Though it is Snapshot, it is well tested and so don't be scared about the stability. And it has quite some fixes and enhancements from the previous builds.

``` scala

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

libraryDependencies += "com.tuplejump" %% "calliope" % "0.9.4-EA-SNAPSHOT"

```

If you still see the issue with this build we can get on a call and try to debug it together.

**Comment by sonyjv** [comment]
Thanks @milliondreams for your response. 

Tried to run with Calliope 0.9.4-EA-SNAPSHOT, but getting the following error. Is it that this version of Calliope requires Spark 1.0.0. I am trying to run on 0.9.1.

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.SparkContext.broadcast(Ljava/lang/Object;Lscala/reflect/ClassTag;)Lorg/apache/spark/broadcast/Broadcast;
        at com.tuplejump.calliope.cql3.Cql3CassandraRDD.<init>(Cql3CassandraRDD.scala:57)
        at com.tuplejump.calliope.cql3.Cql3CassandraSparkContext.cql3Cassandra(Cql3CassandraSparkContext.scala:142)

Thanks,
Sony

**Comment by milliondreams** [comment]
Yes It is built against 1.0.0 :(

Some questions about working with 0.9.0-U1-C2-EA  -
1. Does your code run against standard C*? 
2. What build of Cassandra did you run against?
3. Can you share the CASBuilder configuration part of code here?

**Comment by sonyjv** [comment]
Hi Rohit, 

Please find my answers
1. In our in house cluster the code really worked well. 
2. I used both DSE 4.0 and DSE 4.5 in local cluster and was working. In EC2 I was using DSE 4.5
3. Here is the configuration 
   val casOffer = CasBuilder.cql3.withColumnFamily("mydb", "offer").onHost(cassandra_ip).onPort(cassandra_port);

In EC2 I have setup Spark cluster using ami-72320f37 from apache and Cassandra cluster using ami-3cf7c979 from DataStax.

Regards,
Sony

**Comment by sonyjv** [comment]
Hi Rohit,

In the meantime I migrated my code to Spark 1.0.0 and build with Calliope 0.9.4-EA-SNAPSHOT. While running the application in our in house cluster I am getting the following error. 

It seems JsonClass is part of an older version of jackson-core-asl:1.8.8. But cassandra-all:2.0.7 (on which the Calliope has dependency) has moved to jackson-core-asl:1.9.2 where JsonClass is not present any more.

Did you encounter this issue in your testing with cassandra-all:2.0.7?

java.lang.NoClassDefFoundError: org/codehaus/jackson/annotate/JsonClass
        at org.codehaus.jackson.map.introspect.JacksonAnnotationIntrospector.findDeserializationType(JacksonAnnotationIntrospector.java:524)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:732)
        at org.codehaus.jackson.map.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:229)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:386)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:307)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:287)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:136)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:157)
        at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2468)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2402)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1602)
        at org.apache.cassandra.utils.FBUtilities.fromJsonList(FBUtilities.java:564)
        at com.tuplejump.calliope.hadoop.cql3.CqlPagingRecordReader.retrieveKeys(CqlPagingRecordReader.java:686)
        at com.tuplejump.calliope.hadoop.cql3.CqlPagingRecordReader.initialize(CqlPagingRecordReader.java:156)
        at com.tuplejump.calliope.cql3.Cql3CassandraRDD$$anon$1.<init>(Cql3CassandraRDD.scala:77)
        at com.tuplejump.calliope.cql3.Cql3CassandraRDD.compute(Cql3CassandraRDD.scala:66)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        at org.apache.spark.rdd.FilteredRDD.compute(FilteredRDD.scala:34)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:158)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.Task.run(Task.scala:51)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

**Comment by milliondreams** [comment]
@sonyjv Will it be possible for us to get on a call and hopefully do a screenshare too? We can do a Hangout or I can do a phone call too. Just mail me and we can take it from there - rohit [at] tuplejump [dot] com

**Comment by milliondreams** [comment]
@sonyjv 

Though the Cassandra dependency on Jackson is upgraded, Spark still uses the old library.

Can you share your build dependency settings and submitJob/addJar code?

**Comment by sonyjv** [comment]
Hi Rohit,

The issue was with the Spark 1.0.0 CDH4 prebuilt published at Spark download page. I download Spark code and build myself. This solved the issue for me. 

In fact we have migrated to Spark 1.0.1 and Calliope (0.9.4-EA-SNAPSHOT) works like a charm. 

 Thanks a lot for your support.
